export const WeatherType = {

	"Gradient" : 'linear-gradient(to bottom right, #c31432, #240b36)',

	"Partly cloudy": 'url(/photos/PartlyCloudy.jpg)',
	"Clear": 'url(/photos/Clear.jpg)',
	"Sunny": 'url(/photos/Sunny.jpg)',
	"Mist": 'url(/photos/Mist.jpg)',
	"Cloudy": 'url(/photos/Cloudy.jpg)',
	"Overcast": 'url(/photos/Overcast.jpg)',
	"Patchy rain possible": 'url(/photos/PatchyRain.jpg)',
	"Patchy snow possible": 'url(/photos/LightSnow.jpg)',
	"Patchy sleet possible": 'url(/photos/Snow.jpg)',
	"Patchy freezing drizzle possible": 'url(/photos/PatchyRain.jpg)',
	"Thundery outbreaks possible": 'url(/photos/Thunder.jpg)',
	"Blowing snow": 'url(/photos/Snow.jpg)',
	"Blizzard": 'url(/photos/Snow.jpg)',
	"Fog": 'url(/photos/Fog.jpg)',
	"Freezing fog": 'url(/photos/Fog.jpg)',
	"Patchy light drizzle": 'url(/photos/PatchyRain.jpg)',
	"Light drizzle": 'url(/photos/PatchyRain.jpg)',
	"Freezing drizzle": 'url(/photos/LightSnow.jpg)',
	"Heavy freezing drizzle": 'url(/photos/Rain.jpg)',
	"Patchy light rain": 'url(/photos/LightRain.jpg)',
	"Light rain": 'url(/photos/LightRain.jpg)',
	"Moderate rain at times": 'url(/photos/PatchyRain.jpg)',
	"Moderate rain": 'url(/photos/LightRain.jpg)',
	"Heavy rain at times": 'url(/photos/HeavyRain.jpg)',
	"Heavy rain": 'url(/photos/HeavyRain.jpg)',
	"Light freezing rain": 'url(/photos/LightRain.jpg)',
	"Moderate or heavy freezing rain": 'url(/photos/Rain.jpg)',
	"Light sleet": 'url(/photos/LightSnow.jpg)',
	"Moderate or heavy sleet": 'url(/photos/Snow.jpg)',
	"Patchy light snow": 'url(/photos/LightSnow.jpg)',
	"Light snow": 'url(/photos/LightSnow.jpg)',
	"Patchy moderate snow": 'url(/photos/LightSnow.jpg)',
	"Moderate snow": 'url(/photos/Snow.jpg)',
	"Patchy heavy snow": 'url(/photos/Snow.jpg)',
	"Heavy snow": 'url(/photos/Snow.jpg)',
	"Ice pellets": 'url(/photos/Icey.jpg)',
	"Light rain shower": 'url(/photos/LightRain.jpg)',
	"Moderate or heavy rain shower": 'url(/photos/HeavyRain.jpg)',
	"Torrential rain shower": 'url(/photos/HeavyRain.jpg)',
	"Light sleet showers": 'url(/photos/LightRain.jpg)',
	"Moderate or heavy sleet showers": 'url(/photos/LightRain.jpg)',
	"Light snow showers": 'url(/photos/LightSnow.jpg)',
	"Moderate or heavy snow showers": 'url(/photos/Snow.jpg)',
	"Light showers of ice pellets": 'url(/photos/Icey.jpg)',
	"Moderate or heavy showers of ice pellets": 'url(/photos/HeavyRain.jpg)',
	"Patchy light rain with thunder": 'url(/photos/ThunderCloud.jpg)',
	"Moderate or heavy rain with thunder": 'url(/photos/HeavyRain.jpg)',
	"Patchy light snow with thunder": 'url(/photos/ThunderCloud.jpg)',
	"Moderate or heavy snow with thunder": 'url(/photos/ThunderCloud.jpg)',
}