export const WeatherType = {

	"Gradient" : 'linear-gradient(to bottom right, #c31432, #240b36)',

	"Partly cloudy": `url(${process.env.PUBLIC_URL}/photos/PartlyCloudy.jpg)`,
	"Clear": `url(${process.env.PUBLIC_URL}/photos/Clear.jpg)`,
	"Sunny": `url(${process.env.PUBLIC_URL}/photos/Sunny.jpg)`,
	"Mist": `url(${process.env.PUBLIC_URL}/photos/Mist.jpg)`,
	"Cloudy": `url(${process.env.PUBLIC_URL}/photos/Cloudy.jpg)`,
	"Overcast": `url(${process.env.PUBLIC_URL}/photos/Overcast.jpg)`,
	"Patchy rain possible": `url(${process.env.PUBLIC_URL}/photos/PatchyRain.jpg)`,
	"Patchy snow possible": `url(${process.env.PUBLIC_URL}/photos/LightSnow.jpg)`,
	"Patchy sleet possible": `url(${process.env.PUBLIC_URL}/photos/Snow.jpg)`,
	"Patchy freezing drizzle possible": `url(${process.env.PUBLIC_URL}/photos/PatchyRain.jpg)`,
	"Thundery outbreaks possible": `url(${process.env.PUBLIC_URL}/photos/Thunder.jpg)`,
	"Blowing snow": `url(${process.env.PUBLIC_URL}/photos/Snow.jpg)`,
	"Blizzard": `url(${process.env.PUBLIC_URL}/photos/Snow.jpg)`,
	"Fog": `url(${process.env.PUBLIC_URL}/photos/Fog.jpg)`,
	"Freezing fog": `url(${process.env.PUBLIC_URL}/photos/Fog.jpg)`,
	"Patchy light drizzle": `url(${process.env.PUBLIC_URL}/photos/PatchyRain.jpg)`,
	"Light drizzle": `url(${process.env.PUBLIC_URL}/photos/PatchyRain.jpg)`,
	"Freezing drizzle": `url(${process.env.PUBLIC_URL}/photos/LightSnow.jpg)`,
	"Heavy freezing drizzle": `url(${process.env.PUBLIC_URL}/photos/Rain.jpg)`,
	"Patchy light rain": `url(${process.env.PUBLIC_URL}/photos/LightRain.jpg)`,
	"Light rain": `url(${process.env.PUBLIC_URL}/photos/LightRain.jpg)`,
	"Moderate rain at times": `url(${process.env.PUBLIC_URL}/photos/PatchyRain.jpg)`,
	"Moderate rain": `url(${process.env.PUBLIC_URL}/photos/LightRain.jpg)`,
	"Heavy rain at times": `url(${process.env.PUBLIC_URL}/photos/HeavyRain.jpg)`,
	"Heavy rain": `url(${process.env.PUBLIC_URL}/photos/HeavyRain.jpg)`,
	"Light freezing rain": `url(${process.env.PUBLIC_URL}/photos/LightRain.jpg)`,
	"Moderate or heavy freezing rain": `url(${process.env.PUBLIC_URL}/photos/Rain.jpg)`,
	"Light sleet": `url(${process.env.PUBLIC_URL}/photos/LightSnow.jpg)`,
	"Moderate or heavy sleet": `url(${process.env.PUBLIC_URL}/photos/Snow.jpg)`,
	"Patchy light snow": `url(${process.env.PUBLIC_URL}/photos/LightSnow.jpg)`,
	"Light snow": `url(${process.env.PUBLIC_URL}/photos/LightSnow.jpg)`,
	"Patchy moderate snow": `url(${process.env.PUBLIC_URL}/photos/LightSnow.jpg)`,
	"Moderate snow": `url(${process.env.PUBLIC_URL}/photos/Snow.jpg)`,
	"Patchy heavy snow": `url(${process.env.PUBLIC_URL}/photos/Snow.jpg)`,
	"Heavy snow": `url(${process.env.PUBLIC_URL}/photos/Snow.jpg)`,
	"Ice pellets": `url(${process.env.PUBLIC_URL}/photos/Icey.jpg)`,
	"Light rain shower": `url(${process.env.PUBLIC_URL}/photos/LightRain.jpg)`,
	"Moderate or heavy rain shower": `url(${process.env.PUBLIC_URL}/photos/HeavyRain.jpg)`,
	"Torrential rain shower": `url(${process.env.PUBLIC_URL}/photos/HeavyRain.jpg)`,
	"Light sleet showers": `url(${process.env.PUBLIC_URL}/photos/LightRain.jpg)`,
	"Moderate or heavy sleet showers": `url(${process.env.PUBLIC_URL}/photos/LightRain.jpg)`,
	"Light snow showers": `url(${process.env.PUBLIC_URL}/photos/LightSnow.jpg)`,
	"Moderate or heavy snow showers": `url(${process.env.PUBLIC_URL}/photos/Snow.jpg)`,
	"Light showers of ice pellets": `url(${process.env.PUBLIC_URL}/photos/Icey.jpg)`,
	"Moderate or heavy showers of ice pellets": `url(${process.env.PUBLIC_URL}/photos/HeavyRain.jpg)`,
	"Patchy light rain with thunder": `url(${process.env.PUBLIC_URL}/photos/ThunderCloud.jpg)`,
	"Moderate or heavy rain with thunder": `url(${process.env.PUBLIC_URL}/photos/HeavyRain.jpg)`,
	"Patchy light snow with thunder": `url(${process.env.PUBLIC_URL}/photos/ThunderCloud.jpg)`,
	"Moderate or heavy snow with thunder": `url(${process.env.PUBLIC_URL}/photos/ThunderCloud.jpg)`,
}